// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmoviCrud.Data;

#nullable disable

namespace filmoviCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.Property<int>("FilmoviId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReziseriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmoviId", "ReziseriId");

                    b.HasIndex("ReziseriId");

                    b.ToTable("FilmReziser");
                });

            modelBuilder.Entity("filmoviCrud.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZanrId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZanrId");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("filmoviCrud.Models.Reziser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Uzrast")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reziseri");
                });

            modelBuilder.Entity("filmoviCrud.Models.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.HasOne("filmoviCrud.Models.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmoviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("filmoviCrud.Models.Reziser", null)
                        .WithMany()
                        .HasForeignKey("ReziseriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("filmoviCrud.Models.Film", b =>
                {
                    b.HasOne("filmoviCrud.Models.Zanr", "Zanr")
                        .WithMany("Filmovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("filmoviCrud.Models.Zanr", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
