// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmotekaAPI.Data;

#nullable disable

namespace filmotekaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629090048_FilmDostupan")]
    partial class FilmDostupan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.Property<int>("FilmoviId")
                        .HasColumnType("int");

                    b.Property<int>("ReziseriId")
                        .HasColumnType("int");

                    b.HasKey("FilmoviId", "ReziseriId");

                    b.HasIndex("ReziseriId");

                    b.ToTable("FilmReziser");
                });

            modelBuilder.Entity("filmotekaAPI.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Dostupan")
                        .HasColumnType("bit");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZanrId");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("filmotekaAPI.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("filmotekaAPI.Models.Reziser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<int>("Uzrast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reziseri");
                });

            modelBuilder.Entity("filmotekaAPI.Models.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.HasOne("filmotekaAPI.Models.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmoviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("filmotekaAPI.Models.Reziser", null)
                        .WithMany()
                        .HasForeignKey("ReziseriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("filmotekaAPI.Models.Film", b =>
                {
                    b.HasOne("filmotekaAPI.Models.Zanr", "Zanr")
                        .WithMany("Filmovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("filmotekaAPI.Models.Zanr", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
